# Generated by Django 4.1.1 on 2023-01-10 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="お名前")),
                ("height", models.FloatField(verbose_name="身長")),
                (
                    "weight",
                    models.IntegerField(blank=True, null=True, verbose_name="体重"),
                ),
                ("bmi", models.FloatField(blank=True, null=True, verbose_name="BMI")),
                (
                    "appr_w",
                    models.FloatField(blank=True, null=True, verbose_name="適正体重"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "memo",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="メモ"
                    ),
                ),
            ],
            options={
                "db_table": "person",
            },
        ),
    ]
